// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/wxlbd/nutri-baby-server/internal/application/service"
	"github.com/wxlbd/nutri-baby-server/internal/infrastructure/config"
	"github.com/wxlbd/nutri-baby-server/internal/infrastructure/eino/chain"
	"github.com/wxlbd/nutri-baby-server/internal/infrastructure/eino/model"
	"github.com/wxlbd/nutri-baby-server/internal/infrastructure/eino/tools"
	"github.com/wxlbd/nutri-baby-server/internal/infrastructure/logger"
	"github.com/wxlbd/nutri-baby-server/internal/infrastructure/persistence"
	"github.com/wxlbd/nutri-baby-server/internal/infrastructure/wechat"
	"github.com/wxlbd/nutri-baby-server/internal/interface/http/handler"
	"github.com/wxlbd/nutri-baby-server/internal/interface/http/router"
)

// Injectors from wire.go:

// InitApp 初始化应用(Wire自动生成) (去家庭化架构)
func InitApp(cfg *config.Config) (*App, error) {
	db, err := persistence.NewDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := persistence.NewUserRepository(db)
	client, err := persistence.NewRedis(cfg)
	if err != nil {
		return nil, err
	}
	wechatClient := wechat.NewClient(cfg, client)
	authService := service.NewAuthService(userRepository, cfg, wechatClient)
	appVersionRepository := persistence.NewAppVersionRepository(db)
	appVersionService := service.NewAppVersionService(appVersionRepository)
	authHandler := handler.NewAuthHandler(authService, appVersionService)
	babyRepository := persistence.NewBabyRepository(db)
	babyCollaboratorRepository := persistence.NewBabyCollaboratorRepository(db)
	babyInvitationRepository := persistence.NewBabyInvitationRepository(db)
	vaccinePlanTemplateRepository := persistence.NewVaccinePlanTemplateRepository(db)
	babyVaccineScheduleRepository := persistence.NewBabyVaccineScheduleRepository(db, vaccinePlanTemplateRepository)
	zapLogger, err := logger.NewLogger(cfg)
	if err != nil {
		return nil, err
	}
	vaccineScheduleService := service.NewVaccineScheduleService(babyVaccineScheduleRepository, babyRepository, babyCollaboratorRepository, userRepository, zapLogger)
	wechatService := service.NewWechatService(wechatClient, cfg, zapLogger)
	babyService := service.NewBabyService(babyRepository, babyCollaboratorRepository, babyInvitationRepository, userRepository, vaccineScheduleService, wechatService, zapLogger)
	babyHandler := handler.NewBabyHandler(babyService, wechatService)
	feedingRecordRepository := persistence.NewFeedingRecordRepository(db)
	subscribeRepository := persistence.NewSubscribeRepository(db)
	subscriptionCacheRepository := persistence.NewSubscriptionCacheRepository(client)
	subscribeService := service.NewSubscribeService(subscribeRepository, subscriptionCacheRepository, userRepository, wechatService, zapLogger)
	aiAnalysisRepository := persistence.NewAIAnalysisRepository(db)
	dailyTipsRepository := persistence.NewDailyTipsRepository(db)
	toolCallingChatModel, err := model.NewToolCallingChatModel(cfg, zapLogger)
	if err != nil {
		return nil, err
	}
	sleepRecordRepository := persistence.NewSleepRecordRepository(db)
	diaperRecordRepository := persistence.NewDiaperRecordRepository(db)
	growthRecordRepository := persistence.NewGrowthRecordRepository(db)
	dataQueryTools := tools.NewDataQueryTools(feedingRecordRepository, sleepRecordRepository, diaperRecordRepository, growthRecordRepository, babyVaccineScheduleRepository, babyRepository, zapLogger)
	batchDataTools := tools.NewBatchDataTools(babyRepository, feedingRecordRepository, sleepRecordRepository, growthRecordRepository, diaperRecordRepository, zapLogger)
	analysisChainBuilder := chain.NewAnalysisChainBuilder(toolCallingChatModel, dataQueryTools, batchDataTools, zapLogger)
	aiAnalysisService := service.NewAIAnalysisService(aiAnalysisRepository, dailyTipsRepository, babyRepository, analysisChainBuilder, cfg, zapLogger)
	schedulerService := service.NewSchedulerService(babyVaccineScheduleRepository, feedingRecordRepository, userRepository, babyRepository, babyCollaboratorRepository, subscribeService, aiAnalysisService, cfg, zapLogger)
	feedingRecordService := service.NewFeedingRecordService(babyRepository, babyCollaboratorRepository, userRepository, feedingRecordRepository, schedulerService, zapLogger)
	sleepRecordService := service.NewSleepRecordService(babyRepository, babyCollaboratorRepository, userRepository, sleepRecordRepository, zapLogger)
	diaperRecordService := service.NewDiaperRecordService(babyRepository, babyCollaboratorRepository, userRepository, diaperRecordRepository, zapLogger)
	growthRecordService := service.NewGrowthRecordService(babyRepository, babyCollaboratorRepository, userRepository, growthRecordRepository, zapLogger)
	timelineService := service.NewTimelineService(babyRepository, babyCollaboratorRepository, userRepository, feedingRecordService, sleepRecordService, diaperRecordService, growthRecordService, zapLogger)
	recordHandler := handler.NewRecordHandler(feedingRecordService, sleepRecordService, diaperRecordService, growthRecordService, timelineService)
	vaccineScheduleHandler := handler.NewVaccineScheduleHandler(vaccineScheduleService)
	statisticsService := service.NewStatisticsService(babyRepository, babyCollaboratorRepository, feedingRecordRepository, sleepRecordRepository, diaperRecordRepository, growthRecordRepository, userRepository, zapLogger)
	statisticsHandler := handler.NewStatisticsHandler(statisticsService)
	dailyStatsService := service.NewDailyStatsService(babyRepository, babyCollaboratorRepository, userRepository, feedingRecordRepository, sleepRecordRepository, diaperRecordRepository, growthRecordRepository, zapLogger)
	dailyStatsHandler := handler.NewDailyStatsHandler(dailyStatsService)
	subscribeHandler := handler.NewSubscribeHandler(subscribeService, zapLogger)
	syncHandler := handler.NewSyncHandler()
	uploadService := service.NewUploadService(cfg)
	uploadHandler := handler.NewUploadHandler(uploadService)
	aiAnalysisHandler := handler.NewAIAnalysisHandler(aiAnalysisService, zapLogger)
	engine := router.NewRouter(cfg, authHandler, babyHandler, recordHandler, vaccineScheduleHandler, statisticsHandler, dailyStatsHandler, subscribeHandler, syncHandler, uploadHandler, aiAnalysisHandler, aiAnalysisService, zapLogger)
	app := NewApp(cfg, engine, schedulerService, aiAnalysisService, aiAnalysisHandler)
	return app, nil
}
