/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AIAlertCard: typeof import('./src/components/ai/AIAlertCard.vue')['default']
    AIChart: typeof import('./src/components/charts/AIChart.vue')['default']
    AIInsightCard: typeof import('./src/components/ai/AIInsightCard.vue')['default']
    AIScoreCard: typeof import('./src/components/ai/AIScoreCard.vue')['default']
    BabyCollaboratorsPreview: typeof import('./src/components/BabyCollaboratorsPreview.vue')['default']
    CircleProgress: typeof import('./src/components/common/CircleProgress.vue')['default']
    DailyTipsCard: typeof import('./src/components/DailyTipsCard.vue')['default']
    SubscribeGuide: typeof import('./src/components/SubscribeGuide.vue')['default']
    UChart: typeof import('./src/components/UChart.vue')['default']
  }
}
